// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE

import * as Block from "../../node_modules/bs-platform/lib/es6/block.js";
import * as Atdgen_codec_runtime from "../../node_modules/@ahrefs/bs-atdgen-codec-runtime/src/atdgen_codec_runtime.bs.js";

var partial_arg = Atdgen_codec_runtime.Encode[/* int */5];

var partial_arg$1 = Atdgen_codec_runtime.Encode[/* option_as_constr */23];

function write__2(param) {
  return partial_arg$1(partial_arg, param);
}

var read__2 = Atdgen_codec_runtime.Decode[/* option_as_constr */25](Atdgen_codec_runtime.Decode[/* int */4]);

var write_timeEstimate = Atdgen_codec_runtime.Encode[/* make */0]((function (t) {
        return Atdgen_codec_runtime.Encode[/* obj */14](/* :: */Block.simpleVariant("::", [
                      Atdgen_codec_runtime.Encode[/* field */12](undefined, write__2, "preparation", t[/* preparation */0]),
                      /* :: */Block.simpleVariant("::", [
                          Atdgen_codec_runtime.Encode[/* field */12](undefined, write__2, "cooking", t[/* cooking */1]),
                          /* :: */Block.simpleVariant("::", [
                              Atdgen_codec_runtime.Encode[/* field */12](undefined, write__2, "waiting", t[/* waiting */2]),
                              /* [] */0
                            ])
                        ])
                    ]));
      }));

var read_timeEstimate = Atdgen_codec_runtime.Decode[/* make */0]((function (json) {
        var partial_arg = Atdgen_codec_runtime.Decode[/* field */15];
        var partial_arg$1 = Atdgen_codec_runtime.Decode[/* field */15];
        var partial_arg$2 = Atdgen_codec_runtime.Decode[/* field */15];
        return /* record */Block.record([
                  "preparation",
                  "cooking",
                  "waiting"
                ], [
                  Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                          return partial_arg("preparation", read__2, param);
                        }), json),
                  Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                          return partial_arg$1("cooking", read__2, param);
                        }), json),
                  Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                          return partial_arg$2("waiting", read__2, param);
                        }), json)
                ]);
      }));

var write_category = Atdgen_codec_runtime.Encode[/* make */0]((function (x) {
        if (x >= -295650606) {
          if (x >= 179445857) {
            if (x >= 430827387) {
              return Atdgen_codec_runtime.Encode[/* constr0 */19]("Drinks");
            } else {
              return Atdgen_codec_runtime.Encode[/* constr0 */19]("Salad");
            }
          } else if (x >= -249281658) {
            return Atdgen_codec_runtime.Encode[/* constr0 */19]("Dessert");
          } else {
            return Atdgen_codec_runtime.Encode[/* constr0 */19]("Dinner");
          }
        } else if (x !== -367790927) {
          if (x >= -354446661) {
            return Atdgen_codec_runtime.Encode[/* constr0 */19]("Breakfast");
          } else {
            return Atdgen_codec_runtime.Encode[/* constr0 */19]("Other");
          }
        } else {
          return Atdgen_codec_runtime.Encode[/* constr0 */19]("SideDish");
        }
      }));

var read_category = Atdgen_codec_runtime.Decode[/* enum */23](/* :: */Block.simpleVariant("::", [
        /* tuple */[
          "Dinner",
          /* `Single */Block.polyVar("Single", [
              -306849112,
              /* Dinner */-295650606
            ])
        ],
        /* :: */Block.simpleVariant("::", [
            /* tuple */[
              "Dessert",
              /* `Single */Block.polyVar("Single", [
                  -306849112,
                  /* Dessert */-249281658
                ])
            ],
            /* :: */Block.simpleVariant("::", [
                /* tuple */[
                  "Breakfast",
                  /* `Single */Block.polyVar("Single", [
                      -306849112,
                      /* Breakfast */-354446661
                    ])
                ],
                /* :: */Block.simpleVariant("::", [
                    /* tuple */[
                      "Salad",
                      /* `Single */Block.polyVar("Single", [
                          -306849112,
                          /* Salad */179445857
                        ])
                    ],
                    /* :: */Block.simpleVariant("::", [
                        /* tuple */[
                          "SideDish",
                          /* `Single */Block.polyVar("Single", [
                              -306849112,
                              /* SideDish */-367790927
                            ])
                        ],
                        /* :: */Block.simpleVariant("::", [
                            /* tuple */[
                              "Drinks",
                              /* `Single */Block.polyVar("Single", [
                                  -306849112,
                                  /* Drinks */430827387
                                ])
                            ],
                            /* :: */Block.simpleVariant("::", [
                                /* tuple */[
                                  "Other",
                                  /* `Single */Block.polyVar("Single", [
                                      -306849112,
                                      /* Other */-912009552
                                    ])
                                ],
                                /* [] */0
                              ])
                          ])
                      ])
                  ])
              ])
          ])
      ]));

var partial_arg$2 = Atdgen_codec_runtime.Encode[/* string */3];

var partial_arg$3 = Atdgen_codec_runtime.Encode[/* option_as_constr */23];

function write__1(param) {
  return partial_arg$3(partial_arg$2, param);
}

var read__1 = Atdgen_codec_runtime.Decode[/* option_as_constr */25](Atdgen_codec_runtime.Decode[/* string */7]);

var write_recipe = Atdgen_codec_runtime.Encode[/* make */0]((function (t) {
        return Atdgen_codec_runtime.Encode[/* obj */14](/* :: */Block.simpleVariant("::", [
                      Atdgen_codec_runtime.Encode[/* field */12](undefined, Atdgen_codec_runtime.Encode[/* string */3], "id", t[/* id */0]),
                      /* :: */Block.simpleVariant("::", [
                          Atdgen_codec_runtime.Encode[/* field */12](undefined, Atdgen_codec_runtime.Encode[/* string */3], "title", t[/* title */1]),
                          /* :: */Block.simpleVariant("::", [
                              Atdgen_codec_runtime.Encode[/* field */12](undefined, Atdgen_codec_runtime.Encode[/* string */3], "description", t[/* description */2]),
                              /* :: */Block.simpleVariant("::", [
                                  Atdgen_codec_runtime.Encode[/* field */12](undefined, write_timeEstimate, "timeEstimate", t[/* timeEstimate */3]),
                                  /* :: */Block.simpleVariant("::", [
                                      Atdgen_codec_runtime.Encode[/* field */12](undefined, write_category, "category", t[/* category */4]),
                                      /* :: */Block.simpleVariant("::", [
                                          Atdgen_codec_runtime.Encode[/* field */12](undefined, Atdgen_codec_runtime.Encode[/* float */4], "portions", t[/* portions */5]),
                                          /* :: */Block.simpleVariant("::", [
                                              Atdgen_codec_runtime.Encode[/* field */12](undefined, write__1, "portionIdentifier", t[/* portionIdentifier */6]),
                                              /* [] */0
                                            ])
                                        ])
                                    ])
                                ])
                            ])
                        ])
                    ]));
      }));

var read_recipe = Atdgen_codec_runtime.Decode[/* make */0]((function (json) {
        var partial_arg = Atdgen_codec_runtime.Decode[/* string */7];
        var partial_arg$1 = Atdgen_codec_runtime.Decode[/* field */15];
        var partial_arg$2 = Atdgen_codec_runtime.Decode[/* string */7];
        var partial_arg$3 = Atdgen_codec_runtime.Decode[/* field */15];
        var partial_arg$4 = Atdgen_codec_runtime.Decode[/* string */7];
        var partial_arg$5 = Atdgen_codec_runtime.Decode[/* field */15];
        var partial_arg$6 = Atdgen_codec_runtime.Decode[/* field */15];
        var partial_arg$7 = Atdgen_codec_runtime.Decode[/* field */15];
        var partial_arg$8 = Atdgen_codec_runtime.Decode[/* float */5];
        var partial_arg$9 = Atdgen_codec_runtime.Decode[/* field */15];
        var partial_arg$10 = Atdgen_codec_runtime.Decode[/* field */15];
        return /* record */Block.record([
                  "id",
                  "title",
                  "description",
                  "timeEstimate",
                  "category",
                  "portions",
                  "portionIdentifier"
                ], [
                  Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                          return partial_arg$1("id", partial_arg, param);
                        }), json),
                  Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                          return partial_arg$3("title", partial_arg$2, param);
                        }), json),
                  Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                          return partial_arg$5("description", partial_arg$4, param);
                        }), json),
                  Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                          return partial_arg$6("timeEstimate", read_timeEstimate, param);
                        }), json),
                  Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                          return partial_arg$7("category", read_category, param);
                        }), json),
                  Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                          return partial_arg$9("portions", partial_arg$8, param);
                        }), json),
                  Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                          return partial_arg$10("portionIdentifier", read__1, param);
                        }), json)
                ]);
      }));

var write_amount = Atdgen_codec_runtime.Encode[/* make */0]((function (x) {
        var variant = x[0];
        if (variant >= 16828) {
          if (variant >= 3358046) {
            if (variant >= 163705601) {
              return Atdgen_codec_runtime.Encode[/* constr1 */20]("TeaSpoon", Atdgen_codec_runtime.Encode[/* float */4], x[1]);
            } else {
              return Atdgen_codec_runtime.Encode[/* constr1 */20]("Cup", Atdgen_codec_runtime.Encode[/* float */4], x[1]);
            }
          } else if (variant >= 17279) {
            return Atdgen_codec_runtime.Encode[/* constr1 */20]("Ml", Atdgen_codec_runtime.Encode[/* int */5], x[1]);
          } else {
            return Atdgen_codec_runtime.Encode[/* constr1 */20]("Kg", Atdgen_codec_runtime.Encode[/* float */4], x[1]);
          }
        } else if (variant !== 71) {
          if (variant >= 76) {
            return Atdgen_codec_runtime.Encode[/* constr1 */20]("L", Atdgen_codec_runtime.Encode[/* float */4], x[1]);
          } else {
            return Atdgen_codec_runtime.Encode[/* constr1 */20]("TableSpoon", Atdgen_codec_runtime.Encode[/* float */4], x[1]);
          }
        } else {
          return Atdgen_codec_runtime.Encode[/* constr1 */20]("G", Atdgen_codec_runtime.Encode[/* int */5], x[1]);
        }
      }));

var partial_arg$4 = Atdgen_codec_runtime.Decode[/* float */5];

var partial_arg$5 = Atdgen_codec_runtime.Decode[/* map */18];

var partial_arg$6 = Atdgen_codec_runtime.Decode[/* float */5];

var partial_arg$7 = Atdgen_codec_runtime.Decode[/* map */18];

var partial_arg$8 = Atdgen_codec_runtime.Decode[/* float */5];

var partial_arg$9 = Atdgen_codec_runtime.Decode[/* map */18];

var partial_arg$10 = Atdgen_codec_runtime.Decode[/* int */4];

var partial_arg$11 = Atdgen_codec_runtime.Decode[/* map */18];

var partial_arg$12 = Atdgen_codec_runtime.Decode[/* float */5];

var partial_arg$13 = Atdgen_codec_runtime.Decode[/* map */18];

var partial_arg$14 = Atdgen_codec_runtime.Decode[/* int */4];

var partial_arg$15 = Atdgen_codec_runtime.Decode[/* map */18];

var partial_arg$16 = Atdgen_codec_runtime.Decode[/* float */5];

var partial_arg$17 = Atdgen_codec_runtime.Decode[/* map */18];

var read_amount = Atdgen_codec_runtime.Decode[/* enum */23](/* :: */Block.simpleVariant("::", [
        /* tuple */[
          "Cup",
          /* `Decode */Block.polyVar("Decode", [
              427938126,
              (function (param) {
                  return partial_arg$5((function (x) {
                                return /* `Cup */Block.polyVar("Cup", [
                                          3358046,
                                          x
                                        ]);
                              }), partial_arg$4, param);
                })
            ])
        ],
        /* :: */Block.simpleVariant("::", [
            /* tuple */[
              "TableSpoon",
              /* `Decode */Block.polyVar("Decode", [
                  427938126,
                  (function (param) {
                      return partial_arg$7((function (x) {
                                    return /* `TableSpoon */Block.polyVar("TableSpoon", [
                                              -319815677,
                                              x
                                            ]);
                                  }), partial_arg$6, param);
                    })
                ])
            ],
            /* :: */Block.simpleVariant("::", [
                /* tuple */[
                  "TeaSpoon",
                  /* `Decode */Block.polyVar("Decode", [
                      427938126,
                      (function (param) {
                          return partial_arg$9((function (x) {
                                        return /* `TeaSpoon */Block.polyVar("TeaSpoon", [
                                                  163705601,
                                                  x
                                                ]);
                                      }), partial_arg$8, param);
                        })
                    ])
                ],
                /* :: */Block.simpleVariant("::", [
                    /* tuple */[
                      "G",
                      /* `Decode */Block.polyVar("Decode", [
                          427938126,
                          (function (param) {
                              return partial_arg$11((function (x) {
                                            return /* `G */Block.polyVar("G", [
                                                      71,
                                                      x
                                                    ]);
                                          }), partial_arg$10, param);
                            })
                        ])
                    ],
                    /* :: */Block.simpleVariant("::", [
                        /* tuple */[
                          "Kg",
                          /* `Decode */Block.polyVar("Decode", [
                              427938126,
                              (function (param) {
                                  return partial_arg$13((function (x) {
                                                return /* `Kg */Block.polyVar("Kg", [
                                                          16828,
                                                          x
                                                        ]);
                                              }), partial_arg$12, param);
                                })
                            ])
                        ],
                        /* :: */Block.simpleVariant("::", [
                            /* tuple */[
                              "Ml",
                              /* `Decode */Block.polyVar("Decode", [
                                  427938126,
                                  (function (param) {
                                      return partial_arg$15((function (x) {
                                                    return /* `Ml */Block.polyVar("Ml", [
                                                              17279,
                                                              x
                                                            ]);
                                                  }), partial_arg$14, param);
                                    })
                                ])
                            ],
                            /* :: */Block.simpleVariant("::", [
                                /* tuple */[
                                  "L",
                                  /* `Decode */Block.polyVar("Decode", [
                                      427938126,
                                      (function (param) {
                                          return partial_arg$17((function (x) {
                                                        return /* `L */Block.polyVar("L", [
                                                                  76,
                                                                  x
                                                                ]);
                                                      }), partial_arg$16, param);
                                        })
                                    ])
                                ],
                                /* [] */0
                              ])
                          ])
                      ])
                  ])
              ])
          ])
      ]));

var write_ingredient = Atdgen_codec_runtime.Encode[/* make */0]((function (t) {
        return Atdgen_codec_runtime.Encode[/* obj */14](/* :: */Block.simpleVariant("::", [
                      Atdgen_codec_runtime.Encode[/* field */12](undefined, Atdgen_codec_runtime.Encode[/* string */3], "id", t[/* id */0]),
                      /* :: */Block.simpleVariant("::", [
                          Atdgen_codec_runtime.Encode[/* field */12](undefined, write_amount, "amount", t[/* amount */1]),
                          /* :: */Block.simpleVariant("::", [
                              Atdgen_codec_runtime.Encode[/* field */12](undefined, Atdgen_codec_runtime.Encode[/* string */3], "name", t[/* name */2]),
                              /* :: */Block.simpleVariant("::", [
                                  Atdgen_codec_runtime.Encode[/* field */12](undefined, Atdgen_codec_runtime.Encode[/* string */3], "nutritionId", t[/* nutritionId */3]),
                                  /* [] */0
                                ])
                            ])
                        ])
                    ]));
      }));

var read_ingredient = Atdgen_codec_runtime.Decode[/* make */0]((function (json) {
        var partial_arg = Atdgen_codec_runtime.Decode[/* string */7];
        var partial_arg$1 = Atdgen_codec_runtime.Decode[/* field */15];
        var partial_arg$2 = Atdgen_codec_runtime.Decode[/* field */15];
        var partial_arg$3 = Atdgen_codec_runtime.Decode[/* string */7];
        var partial_arg$4 = Atdgen_codec_runtime.Decode[/* field */15];
        var partial_arg$5 = Atdgen_codec_runtime.Decode[/* string */7];
        var partial_arg$6 = Atdgen_codec_runtime.Decode[/* field */15];
        return /* record */Block.record([
                  "id",
                  "amount",
                  "name",
                  "nutritionId"
                ], [
                  Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                          return partial_arg$1("id", partial_arg, param);
                        }), json),
                  Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                          return partial_arg$2("amount", read_amount, param);
                        }), json),
                  Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                          return partial_arg$4("name", partial_arg$3, param);
                        }), json),
                  Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                          return partial_arg$6("nutritionId", partial_arg$5, param);
                        }), json)
                ]);
      }));

var partial_arg$18 = Atdgen_codec_runtime.Encode[/* list */8];

function write__3(param) {
  return partial_arg$18(write_ingredient, param);
}

var partial_arg$19 = Atdgen_codec_runtime.Decode[/* list */11];

function read__3(param) {
  return partial_arg$19(read_ingredient, param);
}

var write_ingredientList = Atdgen_codec_runtime.Encode[/* make */0]((function (t) {
        return Atdgen_codec_runtime.Encode[/* obj */14](/* :: */Block.simpleVariant("::", [
                      Atdgen_codec_runtime.Encode[/* field */12](undefined, Atdgen_codec_runtime.Encode[/* string */3], "id", t[/* id */0]),
                      /* :: */Block.simpleVariant("::", [
                          Atdgen_codec_runtime.Encode[/* field */12](undefined, write__3, "ingredients", t[/* ingredients */1]),
                          /* :: */Block.simpleVariant("::", [
                              Atdgen_codec_runtime.Encode[/* field */12](undefined, Atdgen_codec_runtime.Encode[/* string */3], "title", t[/* title */2]),
                              /* [] */0
                            ])
                        ])
                    ]));
      }));

var read_ingredientList = Atdgen_codec_runtime.Decode[/* make */0]((function (json) {
        var partial_arg = Atdgen_codec_runtime.Decode[/* string */7];
        var partial_arg$1 = Atdgen_codec_runtime.Decode[/* field */15];
        var partial_arg$2 = Atdgen_codec_runtime.Decode[/* field */15];
        var partial_arg$3 = Atdgen_codec_runtime.Decode[/* string */7];
        var partial_arg$4 = Atdgen_codec_runtime.Decode[/* field */15];
        return /* record */Block.record([
                  "id",
                  "ingredients",
                  "title"
                ], [
                  Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                          return partial_arg$1("id", partial_arg, param);
                        }), json),
                  Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                          return partial_arg$2("ingredients", read__3, param);
                        }), json),
                  Atdgen_codec_runtime.Decode[/* decode */1]((function (param) {
                          return partial_arg$4("title", partial_arg$3, param);
                        }), json)
                ]);
      }));

export {
  read_timeEstimate ,
  write_timeEstimate ,
  read_category ,
  write_category ,
  read_recipe ,
  write_recipe ,
  read_amount ,
  write_amount ,
  read_ingredient ,
  write_ingredient ,
  read_ingredientList ,
  write_ingredientList ,
  
}
/* read__2 Not a pure module */
