// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE

import * as Block from "../../node_modules/bs-platform/lib/es6/block.js";
import * as React from "react";

function Layout$Root(Props) {
  var children = Props.children;
  return React.createElement("div", undefined, children);
}

var Root = /* module */Block.localModule(["make"], [Layout$Root]);

export {
  Root ,
  
}
/* react Not a pure module */
