// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE

import * as Block from "../node_modules/bs-platform/lib/es6/block.js";
import * as React from "react";
import * as Layout from "./Components/Layout.bs.js";
import * as ReactDOMRe from "../node_modules/reason-react/src/ReactDOMRe.js";
import * as NutrientList from "./Components/NutrientList.bs.js";
import * as FoodAutoComplete from "./Components/FoodAutoComplete.bs.js";

function App$App(Props) {
  return React.createElement(Layout.Root[/* make */0], {
              children: null
            }, React.createElement("div", undefined, React.createElement(FoodAutoComplete.make, { })), React.createElement("div", undefined, React.createElement(NutrientList.make, { })));
}

var App = /* module */Block.localModule(["make"], [App$App]);

ReactDOMRe.renderToElementWithId(React.createElement(App$App, { }), "app");

export {
  App ,
  
}
/*  Not a pure module */
