// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE


function capitalize(str) {
  return (str.charAt(0).toUpperCase() + str).slice(1);
}

export {
  capitalize ,
  
}
/* No side effect */
